# Generated by Django 5.1.3 on 2024-12-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('AM', 'Adulto Mayor'), ('IN', 'Instructor')], default='AM', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('duracion', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=200)),
                ('usuario_rut', models.CharField(max_length=20)),
                ('dias', models.CharField(max_length=255)),
                ('confirmacion', models.BooleanField(default=False)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaMuni.taller')),
            ],
        ),
    ]
