# Generated by Django 5.1.3 on 2024-12-01 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaMuni', '0003_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.PositiveIntegerField()),
                ('duracion', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=100)),
                ('usuario_rut', models.CharField(max_length=20)),
                ('dias_seleccionado', models.CharField(max_length=255)),
                ('confirmacion', models.BooleanField(default=False)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaMuni.taller')),
            ],
        ),
    ]
