# Generated by Django 5.1.3 on 2024-12-01 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaMuni', '0005_alter_taller_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='dias_seleccionado',
            new_name='dias',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
