# Generated by Django 5.1.3 on 2024-12-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaMuni', '0006_rename_dias_seleccionado_inscripcion_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario_nombre',
            field=models.CharField(max_length=200),
        ),
    ]
