# Generated by Django 5.1.3 on 2024-12-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaMuni', '0007_alter_inscripcion_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('AM', 'Adulto Mayor'), ('IN', 'Instructor')], default='AM', max_length=2),
        ),
    ]
