# Generated by Django 5.1.3 on 2024-12-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaMuni', '0008_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('AM', 'Adulto Mayor'), ('IN', 'Instructor')], default='AM', max_length=15),
        ),
    ]
